# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f55bb8fd662dce64aa2fba6018b40cfc986989c9f26aa421def3a7bba22c8a08f99528a970c96da7ed8cfde2aae49fb90b87df3cd6331daccda4fa1da35d3e7

test:
  secret_key_base: 21bd97686426c69055ad7bb8f3e9b10d6c8ef89299bf6a5daac888929cd833e1ebbb4887b6f62b2eb874e62f0d7171db80c59a0548911a4a7ee7734b0f536884

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
